---
all:
  children:
    domain_controllers:
      hosts:
        windows-vm.nat.net:
          ansible_host: 10.0.3.6
          ansible_user: adminuser
            #      ansible_password: "AdminP@ssw0rd"  # Use ansible-vault for production
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985  

  vars:
    #ansible_user: "adminuser"
    ansible_password: "{{ domain_admin_password }}"
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_read_timeout_sec: 120

