---
all:
  children:
    domain_controllers:
      hosts:
        windows-vm.nat.net:
          ansible_host: 10.0.3.6
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
