---
- name: Server Health Check
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true
  vars:
    inventory_servers: "{{ groups['servers'] }}"
  tasks:
    - name: Run Health Check Playbook
      include: health-check.yml
