---
# Role: ad_computer_management
# Purpose: Check and move server in Active Directory

- name: SERVER | Include server check tasks
  ansible.builtin.include_tasks: check_server.yml

- name: SERVER | Include server move tasks
  ansible.builtin.include_tasks: move_server.yml
  when: server_exists and not enable_dry_run | bool