all:
  hosts:
    winserver1:
      ansible_host: 10.0.3.11
      ansible_user: adminuser
      ansible_password: "{{ windows_local_admin_password }}"
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_scheme: http
      ansible_port: 5985

  vars:
    # Domain Configuration
    domain_name: "nat.net"
    domain_admin_user: "adminuser@nat.net"
    domain_ou_path: "OU=Computers,DC=nat,DC=net"
    force_reboot: true
