---
- name: Add fstab Entries
  hosts: all
  become_user: root
  become_method: sudo
  gather_facts: false
  become: true  

  tasks:
    - name: Add fstab entries
      lineinfile:
        path: /etc/fstab
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - "/dev/sda1  /mnt/data  ext4  defaults  0  0"
        - "/dev/sdb1  /mnt/backups  ext4  defaults  0  0"
